// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PA.Data;

#nullable disable

namespace PA.Data.Migrations
{
    [DbContext(typeof(JobContext))]
    partial class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("PA.Domain.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("PredictedViews")
                        .HasColumnType("INTEGER")
                        .HasColumnName("predicted_views");

                    b.Property<int>("TotalJobs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_jobs");

                    b.Property<int>("TotalViews")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_views");

                    b.HasKey("Id");

                    b.ToTable("jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
